//nolint

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.8
// source: bubble_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientInfo_Gender int32

const (
	ClientInfo_UNKNOWN ClientInfo_Gender = 0
	ClientInfo_MALE    ClientInfo_Gender = 1
	ClientInfo_FEMALE  ClientInfo_Gender = 2
)

// Enum value maps for ClientInfo_Gender.
var (
	ClientInfo_Gender_name = map[int32]string{
		0: "UNKNOWN",
		1: "MALE",
		2: "FEMALE",
	}
	ClientInfo_Gender_value = map[string]int32{
		"UNKNOWN": 0,
		"MALE":    1,
		"FEMALE":  2,
	}
)

func (x ClientInfo_Gender) Enum() *ClientInfo_Gender {
	p := new(ClientInfo_Gender)
	*p = x
	return p
}

func (x ClientInfo_Gender) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientInfo_Gender) Descriptor() protoreflect.EnumDescriptor {
	return file_bubble_service_proto_enumTypes[0].Descriptor()
}

func (ClientInfo_Gender) Type() protoreflect.EnumType {
	return &file_bubble_service_proto_enumTypes[0]
}

func (x ClientInfo_Gender) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientInfo_Gender.Descriptor instead.
func (ClientInfo_Gender) EnumDescriptor() ([]byte, []int) {
	return file_bubble_service_proto_rawDescGZIP(), []int{0, 0}
}

// ClientInfo
type ClientInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   string            `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Geo      *Geo              `protobuf:"bytes,2,opt,name=geo,proto3" json:"geo,omitempty"`
	Country  string            `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	Language string            `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	Gender   ClientInfo_Gender `protobuf:"varint,5,opt,name=gender,proto3,enum=proto.ClientInfo_Gender" json:"gender,omitempty"`
	Age      int32             `protobuf:"varint,6,opt,name=age,proto3" json:"age,omitempty"`
}

func (x *ClientInfo) Reset() {
	*x = ClientInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bubble_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientInfo) ProtoMessage() {}

func (x *ClientInfo) ProtoReflect() protoreflect.Message {
	mi := &file_bubble_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientInfo.ProtoReflect.Descriptor instead.
func (*ClientInfo) Descriptor() ([]byte, []int) {
	return file_bubble_service_proto_rawDescGZIP(), []int{0}
}

func (x *ClientInfo) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ClientInfo) GetGeo() *Geo {
	if x != nil {
		return x.Geo
	}
	return nil
}

func (x *ClientInfo) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *ClientInfo) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ClientInfo) GetGender() ClientInfo_Gender {
	if x != nil {
		return x.Gender
	}
	return ClientInfo_UNKNOWN
}

func (x *ClientInfo) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

// Request proto
type FeedGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// unique identifier of
	// a client rquest
	RequestId string `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// basic client information
	ClientInfo *ClientInfo `protobuf:"bytes,2,opt,name=client_info,json=clientInfo,proto3" json:"client_info,omitempty"`
}

func (x *FeedGetRequest) Reset() {
	*x = FeedGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bubble_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeedGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedGetRequest) ProtoMessage() {}

func (x *FeedGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bubble_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedGetRequest.ProtoReflect.Descriptor instead.
func (*FeedGetRequest) Descriptor() ([]byte, []int) {
	return file_bubble_service_proto_rawDescGZIP(), []int{1}
}

func (x *FeedGetRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *FeedGetRequest) GetClientInfo() *ClientInfo {
	if x != nil {
		return x.ClientInfo
	}
	return nil
}

// Response proto for FeedGetRequest
type FeedGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RequestId    string         `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ThreadVideos []*ThreadVideo `protobuf:"bytes,2,rep,name=thread_videos,json=threadVideos,proto3" json:"thread_videos,omitempty"`
}

func (x *FeedGetResponse) Reset() {
	*x = FeedGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bubble_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeedGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedGetResponse) ProtoMessage() {}

func (x *FeedGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bubble_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedGetResponse.ProtoReflect.Descriptor instead.
func (*FeedGetResponse) Descriptor() ([]byte, []int) {
	return file_bubble_service_proto_rawDescGZIP(), []int{2}
}

func (x *FeedGetResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *FeedGetResponse) GetThreadVideos() []*ThreadVideo {
	if x != nil {
		return x.ThreadVideos
	}
	return nil
}

var File_bubble_service_proto protoreflect.FileDescriptor

var file_bubble_service_proto_rawDesc = []byte{
	0x0a, 0x14, 0x62, 0x75, 0x62, 0x62, 0x6c, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x09, 0x67,
	0x65, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xea, 0x01, 0x0a, 0x0a, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1c,
	0x0a, 0x03, 0x67, 0x65, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x6f, 0x52, 0x03, 0x67, 0x65, 0x6f, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61,
	0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61,
	0x67, 0x65, 0x12, 0x30, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x52, 0x06, 0x67, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x61, 0x67, 0x65, 0x22, 0x2b, 0x0a, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x08, 0x0a,
	0x04, 0x4d, 0x41, 0x4c, 0x45, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x45, 0x4d, 0x41, 0x4c,
	0x45, 0x10, 0x02, 0x22, 0x63, 0x0a, 0x0e, 0x46, 0x65, 0x65, 0x64, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x49, 0x64, 0x12, 0x32, 0x0a, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69,
	0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x69, 0x0a, 0x0f, 0x46, 0x65, 0x65, 0x64,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x72,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x37, 0x0a, 0x0d, 0x74, 0x68,
	0x72, 0x65, 0x61, 0x64, 0x5f, 0x76, 0x69, 0x64, 0x65, 0x6f, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54, 0x68, 0x72, 0x65, 0x61, 0x64,
	0x56, 0x69, 0x64, 0x65, 0x6f, 0x52, 0x0c, 0x74, 0x68, 0x72, 0x65, 0x61, 0x64, 0x56, 0x69, 0x64,
	0x65, 0x6f, 0x73, 0x32, 0x49, 0x0a, 0x0d, 0x42, 0x75, 0x62, 0x62, 0x6c, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x38, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x46, 0x65, 0x65, 0x64, 0x12,
	0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x65, 0x65, 0x64, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46,
	0x65, 0x65, 0x64, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x23,
	0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x6f, 0x67,
	0x77, 0x61, 0x79, 0x6c, 0x61, 0x62, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bubble_service_proto_rawDescOnce sync.Once
	file_bubble_service_proto_rawDescData = file_bubble_service_proto_rawDesc
)

func file_bubble_service_proto_rawDescGZIP() []byte {
	file_bubble_service_proto_rawDescOnce.Do(func() {
		file_bubble_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_bubble_service_proto_rawDescData)
	})
	return file_bubble_service_proto_rawDescData
}

var file_bubble_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_bubble_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_bubble_service_proto_goTypes = []interface{}{
	(ClientInfo_Gender)(0),  // 0: proto.ClientInfo.Gender
	(*ClientInfo)(nil),      // 1: proto.ClientInfo
	(*FeedGetRequest)(nil),  // 2: proto.FeedGetRequest
	(*FeedGetResponse)(nil), // 3: proto.FeedGetResponse
	(*Geo)(nil),             // 4: proto.Geo
	(*ThreadVideo)(nil),     // 5: proto.ThreadVideo
}
var file_bubble_service_proto_depIdxs = []int32{
	4, // 0: proto.ClientInfo.geo:type_name -> proto.Geo
	0, // 1: proto.ClientInfo.gender:type_name -> proto.ClientInfo.Gender
	1, // 2: proto.FeedGetRequest.client_info:type_name -> proto.ClientInfo
	5, // 3: proto.FeedGetResponse.thread_videos:type_name -> proto.ThreadVideo
	2, // 4: proto.BubbleService.GetFeed:input_type -> proto.FeedGetRequest
	3, // 5: proto.BubbleService.GetFeed:output_type -> proto.FeedGetResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_bubble_service_proto_init() }
func file_bubble_service_proto_init() {
	if File_bubble_service_proto != nil {
		return
	}
	file_geo_proto_init()
	file_thread_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_bubble_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bubble_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeedGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_bubble_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeedGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bubble_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bubble_service_proto_goTypes,
		DependencyIndexes: file_bubble_service_proto_depIdxs,
		EnumInfos:         file_bubble_service_proto_enumTypes,
		MessageInfos:      file_bubble_service_proto_msgTypes,
	}.Build()
	File_bubble_service_proto = out.File
	file_bubble_service_proto_rawDesc = nil
	file_bubble_service_proto_goTypes = nil
	file_bubble_service_proto_depIdxs = nil
}
