//nolint

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.21.12
// source: common_http.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// common Request proto
type RequestWithoutPage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IDToken     string `protobuf:"bytes,1,opt,name=IDToken,proto3" json:"IDToken,omitempty"`
	CustomToken string `protobuf:"bytes,2,opt,name=CustomToken,proto3" json:"CustomToken,omitempty"`
}

func (x *RequestWithoutPage) Reset() {
	*x = RequestWithoutPage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_http_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestWithoutPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestWithoutPage) ProtoMessage() {}

func (x *RequestWithoutPage) ProtoReflect() protoreflect.Message {
	mi := &file_common_http_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestWithoutPage.ProtoReflect.Descriptor instead.
func (*RequestWithoutPage) Descriptor() ([]byte, []int) {
	return file_common_http_proto_rawDescGZIP(), []int{0}
}

func (x *RequestWithoutPage) GetIDToken() string {
	if x != nil {
		return x.IDToken
	}
	return ""
}

func (x *RequestWithoutPage) GetCustomToken() string {
	if x != nil {
		return x.CustomToken
	}
	return ""
}

// common Response proto
type ResponseWithoutPage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode string `protobuf:"bytes,1,opt,name=ErrCode,proto3" json:"ErrCode,omitempty"`
	ErrMsg  string `protobuf:"bytes,2,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
	Data    string `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *ResponseWithoutPage) Reset() {
	*x = ResponseWithoutPage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_http_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseWithoutPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseWithoutPage) ProtoMessage() {}

func (x *ResponseWithoutPage) ProtoReflect() protoreflect.Message {
	mi := &file_common_http_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseWithoutPage.ProtoReflect.Descriptor instead.
func (*ResponseWithoutPage) Descriptor() ([]byte, []int) {
	return file_common_http_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseWithoutPage) GetErrCode() string {
	if x != nil {
		return x.ErrCode
	}
	return ""
}

func (x *ResponseWithoutPage) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *ResponseWithoutPage) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_common_http_proto protoreflect.FileDescriptor

var file_common_http_proto_rawDesc = []byte{
	0x0a, 0x11, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x5f, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x50, 0x0a, 0x12, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x57, 0x69, 0x74, 0x68, 0x6f, 0x75, 0x74, 0x50, 0x61, 0x67, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x49, 0x44, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x49, 0x44, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x43, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x5b, 0x0a, 0x13,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x57, 0x69, 0x74, 0x68, 0x6f, 0x75, 0x74, 0x50,
	0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x45, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x45, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x45,
	0x72, 0x72, 0x4d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x6f, 0x67, 0x77, 0x61, 0x79, 0x6c, 0x61,
	0x62, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_http_proto_rawDescOnce sync.Once
	file_common_http_proto_rawDescData = file_common_http_proto_rawDesc
)

func file_common_http_proto_rawDescGZIP() []byte {
	file_common_http_proto_rawDescOnce.Do(func() {
		file_common_http_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_http_proto_rawDescData)
	})
	return file_common_http_proto_rawDescData
}

var file_common_http_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_http_proto_goTypes = []interface{}{
	(*RequestWithoutPage)(nil),  // 0: proto.RequestWithoutPage
	(*ResponseWithoutPage)(nil), // 1: proto.ResponseWithoutPage
}
var file_common_http_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_http_proto_init() }
func file_common_http_proto_init() {
	if File_common_http_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_http_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestWithoutPage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_http_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseWithoutPage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_http_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_http_proto_goTypes,
		DependencyIndexes: file_common_http_proto_depIdxs,
		MessageInfos:      file_common_http_proto_msgTypes,
	}.Build()
	File_common_http_proto = out.File
	file_common_http_proto_rawDesc = nil
	file_common_http_proto_goTypes = nil
	file_common_http_proto_depIdxs = nil
}
