//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: prompt.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import NIOConcurrencyHelpers
import SwiftProtobuf


/// Usage: instantiate `Proto_PromptSearchClient`, then call methods of this protocol to make API calls.
internal protocol Proto_PromptSearchClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: Proto_PromptSearchClientInterceptorFactoryProtocol? { get }

  func echo(
    _ request: Proto_PromptRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Proto_PromptRequest, Proto_PromptRequest>

  func searchImagesFromPrompt(
    _ request: Proto_PromptRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Proto_PromptRequest, Proto_Prompts>

  func searchStylesFromPrompt(
    _ request: Proto_PromptRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Proto_PromptRequest, Proto_Prompts>

  func searchUsersFromText(
    _ request: Proto_PromptRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Proto_PromptRequest, Proto_CreatorProfiles>

  func searchPromptHistory(
    _ request: Proto_PromptRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Proto_PromptRequest, Proto_Prompts>

  func hidePromptFromUser(
    _ request: Proto_PromptRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Proto_PromptRequest, Proto_Prompt>

  func getFeaturesForPost(
    _ request: Proto_PromptRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Proto_PromptRequest, Proto_Features>

  func searchPostsFromPrompt(
    _ request: Proto_PromptRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Proto_PromptRequest, Proto_ResponseFeed>
}

extension Proto_PromptSearchClientProtocol {
  internal var serviceName: String {
    return "proto.PromptSearch"
  }

  /// Echo back the prompt request
  ///
  /// - Parameters:
  ///   - request: Request to send to Echo.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func echo(
    _ request: Proto_PromptRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Proto_PromptRequest, Proto_PromptRequest> {
    return self.makeUnaryCall(
      path: Proto_PromptSearchClientMetadata.Methods.echo.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeEchoInterceptors() ?? []
    )
  }

  /// Search images from prompt by vector similarity.
  ///
  /// - Parameters:
  ///   - request: Request to send to SearchImagesFromPrompt.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func searchImagesFromPrompt(
    _ request: Proto_PromptRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Proto_PromptRequest, Proto_Prompts> {
    return self.makeUnaryCall(
      path: Proto_PromptSearchClientMetadata.Methods.searchImagesFromPrompt.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSearchImagesFromPromptInterceptors() ?? []
    )
  }

  /// Search styles from prompt by text similarity.
  ///
  /// - Parameters:
  ///   - request: Request to send to SearchStylesFromPrompt.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func searchStylesFromPrompt(
    _ request: Proto_PromptRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Proto_PromptRequest, Proto_Prompts> {
    return self.makeUnaryCall(
      path: Proto_PromptSearchClientMetadata.Methods.searchStylesFromPrompt.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSearchStylesFromPromptInterceptors() ?? []
    )
  }

  /// Search usernames and names
  ///
  /// - Parameters:
  ///   - request: Request to send to SearchUsersFromText.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func searchUsersFromText(
    _ request: Proto_PromptRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Proto_PromptRequest, Proto_CreatorProfiles> {
    return self.makeUnaryCall(
      path: Proto_PromptSearchClientMetadata.Methods.searchUsersFromText.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSearchUsersFromTextInterceptors() ?? []
    )
  }

  /// Search prompts history
  ///
  /// - Parameters:
  ///   - request: Request to send to SearchPromptHistory.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func searchPromptHistory(
    _ request: Proto_PromptRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Proto_PromptRequest, Proto_Prompts> {
    return self.makeUnaryCall(
      path: Proto_PromptSearchClientMetadata.Methods.searchPromptHistory.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSearchPromptHistoryInterceptors() ?? []
    )
  }

  /// Hide prompt from user's history
  ///
  /// - Parameters:
  ///   - request: Request to send to HidePromptFromUser.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func hidePromptFromUser(
    _ request: Proto_PromptRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Proto_PromptRequest, Proto_Prompt> {
    return self.makeUnaryCall(
      path: Proto_PromptSearchClientMetadata.Methods.hidePromptFromUser.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeHidePromptFromUserInterceptors() ?? []
    )
  }

  /// Get feature array for post
  ///
  /// - Parameters:
  ///   - request: Request to send to GetFeaturesForPost.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func getFeaturesForPost(
    _ request: Proto_PromptRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Proto_PromptRequest, Proto_Features> {
    return self.makeUnaryCall(
      path: Proto_PromptSearchClientMetadata.Methods.getFeaturesForPost.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetFeaturesForPostInterceptors() ?? []
    )
  }

  /// Get posts from prompt search
  ///
  /// - Parameters:
  ///   - request: Request to send to SearchPostsFromPrompt.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func searchPostsFromPrompt(
    _ request: Proto_PromptRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Proto_PromptRequest, Proto_ResponseFeed> {
    return self.makeUnaryCall(
      path: Proto_PromptSearchClientMetadata.Methods.searchPostsFromPrompt.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSearchPostsFromPromptInterceptors() ?? []
    )
  }
}

#if compiler(>=5.6)
@available(*, deprecated)
extension Proto_PromptSearchClient: @unchecked Sendable {}
#endif // compiler(>=5.6)

@available(*, deprecated, renamed: "Proto_PromptSearchNIOClient")
internal final class Proto_PromptSearchClient: Proto_PromptSearchClientProtocol {
  private let lock = Lock()
  private var _defaultCallOptions: CallOptions
  private var _interceptors: Proto_PromptSearchClientInterceptorFactoryProtocol?
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions {
    get { self.lock.withLock { return self._defaultCallOptions } }
    set { self.lock.withLockVoid { self._defaultCallOptions = newValue } }
  }
  internal var interceptors: Proto_PromptSearchClientInterceptorFactoryProtocol? {
    get { self.lock.withLock { return self._interceptors } }
    set { self.lock.withLockVoid { self._interceptors = newValue } }
  }

  /// Creates a client for the proto.PromptSearch service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Proto_PromptSearchClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self._defaultCallOptions = defaultCallOptions
    self._interceptors = interceptors
  }
}

internal struct Proto_PromptSearchNIOClient: Proto_PromptSearchClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Proto_PromptSearchClientInterceptorFactoryProtocol?

  /// Creates a client for the proto.PromptSearch service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Proto_PromptSearchClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

#if compiler(>=5.6)
@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal protocol Proto_PromptSearchAsyncClientProtocol: GRPCClient {
  static var serviceDescriptor: GRPCServiceDescriptor { get }
  var interceptors: Proto_PromptSearchClientInterceptorFactoryProtocol? { get }

  func makeEchoCall(
    _ request: Proto_PromptRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Proto_PromptRequest, Proto_PromptRequest>

  func makeSearchImagesFromPromptCall(
    _ request: Proto_PromptRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Proto_PromptRequest, Proto_Prompts>

  func makeSearchStylesFromPromptCall(
    _ request: Proto_PromptRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Proto_PromptRequest, Proto_Prompts>

  func makeSearchUsersFromTextCall(
    _ request: Proto_PromptRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Proto_PromptRequest, Proto_CreatorProfiles>

  func makeSearchPromptHistoryCall(
    _ request: Proto_PromptRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Proto_PromptRequest, Proto_Prompts>

  func makeHidePromptFromUserCall(
    _ request: Proto_PromptRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Proto_PromptRequest, Proto_Prompt>

  func makeGetFeaturesForPostCall(
    _ request: Proto_PromptRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Proto_PromptRequest, Proto_Features>

  func makeSearchPostsFromPromptCall(
    _ request: Proto_PromptRequest,
    callOptions: CallOptions?
  ) -> GRPCAsyncUnaryCall<Proto_PromptRequest, Proto_ResponseFeed>
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Proto_PromptSearchAsyncClientProtocol {
  internal static var serviceDescriptor: GRPCServiceDescriptor {
    return Proto_PromptSearchClientMetadata.serviceDescriptor
  }

  internal var interceptors: Proto_PromptSearchClientInterceptorFactoryProtocol? {
    return nil
  }

  internal func makeEchoCall(
    _ request: Proto_PromptRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Proto_PromptRequest, Proto_PromptRequest> {
    return self.makeAsyncUnaryCall(
      path: Proto_PromptSearchClientMetadata.Methods.echo.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeEchoInterceptors() ?? []
    )
  }

  internal func makeSearchImagesFromPromptCall(
    _ request: Proto_PromptRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Proto_PromptRequest, Proto_Prompts> {
    return self.makeAsyncUnaryCall(
      path: Proto_PromptSearchClientMetadata.Methods.searchImagesFromPrompt.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSearchImagesFromPromptInterceptors() ?? []
    )
  }

  internal func makeSearchStylesFromPromptCall(
    _ request: Proto_PromptRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Proto_PromptRequest, Proto_Prompts> {
    return self.makeAsyncUnaryCall(
      path: Proto_PromptSearchClientMetadata.Methods.searchStylesFromPrompt.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSearchStylesFromPromptInterceptors() ?? []
    )
  }

  internal func makeSearchUsersFromTextCall(
    _ request: Proto_PromptRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Proto_PromptRequest, Proto_CreatorProfiles> {
    return self.makeAsyncUnaryCall(
      path: Proto_PromptSearchClientMetadata.Methods.searchUsersFromText.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSearchUsersFromTextInterceptors() ?? []
    )
  }

  internal func makeSearchPromptHistoryCall(
    _ request: Proto_PromptRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Proto_PromptRequest, Proto_Prompts> {
    return self.makeAsyncUnaryCall(
      path: Proto_PromptSearchClientMetadata.Methods.searchPromptHistory.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSearchPromptHistoryInterceptors() ?? []
    )
  }

  internal func makeHidePromptFromUserCall(
    _ request: Proto_PromptRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Proto_PromptRequest, Proto_Prompt> {
    return self.makeAsyncUnaryCall(
      path: Proto_PromptSearchClientMetadata.Methods.hidePromptFromUser.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeHidePromptFromUserInterceptors() ?? []
    )
  }

  internal func makeGetFeaturesForPostCall(
    _ request: Proto_PromptRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Proto_PromptRequest, Proto_Features> {
    return self.makeAsyncUnaryCall(
      path: Proto_PromptSearchClientMetadata.Methods.getFeaturesForPost.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetFeaturesForPostInterceptors() ?? []
    )
  }

  internal func makeSearchPostsFromPromptCall(
    _ request: Proto_PromptRequest,
    callOptions: CallOptions? = nil
  ) -> GRPCAsyncUnaryCall<Proto_PromptRequest, Proto_ResponseFeed> {
    return self.makeAsyncUnaryCall(
      path: Proto_PromptSearchClientMetadata.Methods.searchPostsFromPrompt.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSearchPostsFromPromptInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
extension Proto_PromptSearchAsyncClientProtocol {
  internal func echo(
    _ request: Proto_PromptRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Proto_PromptRequest {
    return try await self.performAsyncUnaryCall(
      path: Proto_PromptSearchClientMetadata.Methods.echo.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeEchoInterceptors() ?? []
    )
  }

  internal func searchImagesFromPrompt(
    _ request: Proto_PromptRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Proto_Prompts {
    return try await self.performAsyncUnaryCall(
      path: Proto_PromptSearchClientMetadata.Methods.searchImagesFromPrompt.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSearchImagesFromPromptInterceptors() ?? []
    )
  }

  internal func searchStylesFromPrompt(
    _ request: Proto_PromptRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Proto_Prompts {
    return try await self.performAsyncUnaryCall(
      path: Proto_PromptSearchClientMetadata.Methods.searchStylesFromPrompt.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSearchStylesFromPromptInterceptors() ?? []
    )
  }

  internal func searchUsersFromText(
    _ request: Proto_PromptRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Proto_CreatorProfiles {
    return try await self.performAsyncUnaryCall(
      path: Proto_PromptSearchClientMetadata.Methods.searchUsersFromText.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSearchUsersFromTextInterceptors() ?? []
    )
  }

  internal func searchPromptHistory(
    _ request: Proto_PromptRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Proto_Prompts {
    return try await self.performAsyncUnaryCall(
      path: Proto_PromptSearchClientMetadata.Methods.searchPromptHistory.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSearchPromptHistoryInterceptors() ?? []
    )
  }

  internal func hidePromptFromUser(
    _ request: Proto_PromptRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Proto_Prompt {
    return try await self.performAsyncUnaryCall(
      path: Proto_PromptSearchClientMetadata.Methods.hidePromptFromUser.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeHidePromptFromUserInterceptors() ?? []
    )
  }

  internal func getFeaturesForPost(
    _ request: Proto_PromptRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Proto_Features {
    return try await self.performAsyncUnaryCall(
      path: Proto_PromptSearchClientMetadata.Methods.getFeaturesForPost.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeGetFeaturesForPostInterceptors() ?? []
    )
  }

  internal func searchPostsFromPrompt(
    _ request: Proto_PromptRequest,
    callOptions: CallOptions? = nil
  ) async throws -> Proto_ResponseFeed {
    return try await self.performAsyncUnaryCall(
      path: Proto_PromptSearchClientMetadata.Methods.searchPostsFromPrompt.path,
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeSearchPostsFromPromptInterceptors() ?? []
    )
  }
}

@available(macOS 10.15, iOS 13, tvOS 13, watchOS 6, *)
internal struct Proto_PromptSearchAsyncClient: Proto_PromptSearchAsyncClientProtocol {
  internal var channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: Proto_PromptSearchClientInterceptorFactoryProtocol?

  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: Proto_PromptSearchClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

#endif // compiler(>=5.6)

internal protocol Proto_PromptSearchClientInterceptorFactoryProtocol: GRPCSendable {

  /// - Returns: Interceptors to use when invoking 'echo'.
  func makeEchoInterceptors() -> [ClientInterceptor<Proto_PromptRequest, Proto_PromptRequest>]

  /// - Returns: Interceptors to use when invoking 'searchImagesFromPrompt'.
  func makeSearchImagesFromPromptInterceptors() -> [ClientInterceptor<Proto_PromptRequest, Proto_Prompts>]

  /// - Returns: Interceptors to use when invoking 'searchStylesFromPrompt'.
  func makeSearchStylesFromPromptInterceptors() -> [ClientInterceptor<Proto_PromptRequest, Proto_Prompts>]

  /// - Returns: Interceptors to use when invoking 'searchUsersFromText'.
  func makeSearchUsersFromTextInterceptors() -> [ClientInterceptor<Proto_PromptRequest, Proto_CreatorProfiles>]

  /// - Returns: Interceptors to use when invoking 'searchPromptHistory'.
  func makeSearchPromptHistoryInterceptors() -> [ClientInterceptor<Proto_PromptRequest, Proto_Prompts>]

  /// - Returns: Interceptors to use when invoking 'hidePromptFromUser'.
  func makeHidePromptFromUserInterceptors() -> [ClientInterceptor<Proto_PromptRequest, Proto_Prompt>]

  /// - Returns: Interceptors to use when invoking 'getFeaturesForPost'.
  func makeGetFeaturesForPostInterceptors() -> [ClientInterceptor<Proto_PromptRequest, Proto_Features>]

  /// - Returns: Interceptors to use when invoking 'searchPostsFromPrompt'.
  func makeSearchPostsFromPromptInterceptors() -> [ClientInterceptor<Proto_PromptRequest, Proto_ResponseFeed>]
}

internal enum Proto_PromptSearchClientMetadata {
  internal static let serviceDescriptor = GRPCServiceDescriptor(
    name: "PromptSearch",
    fullName: "proto.PromptSearch",
    methods: [
      Proto_PromptSearchClientMetadata.Methods.echo,
      Proto_PromptSearchClientMetadata.Methods.searchImagesFromPrompt,
      Proto_PromptSearchClientMetadata.Methods.searchStylesFromPrompt,
      Proto_PromptSearchClientMetadata.Methods.searchUsersFromText,
      Proto_PromptSearchClientMetadata.Methods.searchPromptHistory,
      Proto_PromptSearchClientMetadata.Methods.hidePromptFromUser,
      Proto_PromptSearchClientMetadata.Methods.getFeaturesForPost,
      Proto_PromptSearchClientMetadata.Methods.searchPostsFromPrompt,
    ]
  )

  internal enum Methods {
    internal static let echo = GRPCMethodDescriptor(
      name: "Echo",
      path: "/proto.PromptSearch/Echo",
      type: GRPCCallType.unary
    )

    internal static let searchImagesFromPrompt = GRPCMethodDescriptor(
      name: "SearchImagesFromPrompt",
      path: "/proto.PromptSearch/SearchImagesFromPrompt",
      type: GRPCCallType.unary
    )

    internal static let searchStylesFromPrompt = GRPCMethodDescriptor(
      name: "SearchStylesFromPrompt",
      path: "/proto.PromptSearch/SearchStylesFromPrompt",
      type: GRPCCallType.unary
    )

    internal static let searchUsersFromText = GRPCMethodDescriptor(
      name: "SearchUsersFromText",
      path: "/proto.PromptSearch/SearchUsersFromText",
      type: GRPCCallType.unary
    )

    internal static let searchPromptHistory = GRPCMethodDescriptor(
      name: "SearchPromptHistory",
      path: "/proto.PromptSearch/SearchPromptHistory",
      type: GRPCCallType.unary
    )

    internal static let hidePromptFromUser = GRPCMethodDescriptor(
      name: "HidePromptFromUser",
      path: "/proto.PromptSearch/HidePromptFromUser",
      type: GRPCCallType.unary
    )

    internal static let getFeaturesForPost = GRPCMethodDescriptor(
      name: "GetFeaturesForPost",
      path: "/proto.PromptSearch/GetFeaturesForPost",
      type: GRPCCallType.unary
    )

    internal static let searchPostsFromPrompt = GRPCMethodDescriptor(
      name: "SearchPostsFromPrompt",
      path: "/proto.PromptSearch/SearchPostsFromPrompt",
      type: GRPCCallType.unary
    )
  }
}

